[package]
name = "flt-rust-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = { version = "^1.2", features = ["fltk-bundled"] }
fltk-theme = "0.4"
notify-rust = "4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["wincon", "winuser", "basetsd", "hidpi", "winnt", "libloaderapi", "fileapi", "hidsdi", "handleapi"] }
native-windows-gui = { version = "1.0.10", default-features=false, features=["tray-notification", "message-window", "menu", "cursor"] }